export enum EpisodesEnum {
  NEW_HOPE = 'NEW_HOPE',
  EMPIRE_STRIKES_BACK = 'EMPIRE_STRIKES_BACK',
  RETURN_OF_THE_JEDI = 'RETURN_OF_THE_JEDI',
  PHANTOM_MENACE = 'PHANTOM_MENACE',
  ATTACK_OF_THE_CLONES = 'ATTACK_OF_THE_CLONES',
  REVENGE_OF_THE_SITH = 'REVENGE_OF_THE_SITH',
  FORCE_AWAKENS = 'FORCE_AWAKENS',
  LAST_JEDI = 'LAST_JEDI',
  RISE_OF_SKYWALKER = 'RISE_OF_SKYWALKER',
}
